### ISSUE TITLE
Calculating the Volume of Smoke Passing Through a Bucket for Indirect Control Evaluation

### ISSUE THREAD

**Issue by XiangZheng2002** [holl-/PDE-Control#7]
Hello,

I'm working with a series of frames in indirect control scenarios and I am trying to figure out how to calculate the volume of smoke passing through each bucket. I have several considerations, such as varying smoke speeds between different buckets. In extreme cases, what if the smoke remains stationary in a bucket, or if there is a continuous flow of smoke through the bucket? How can these situations be distinguished in the calculations?

I would appreciate any insights or methods you might have used in your experiments regarding this issue. Thank you for your time and assistance!

Best regards

**Comment by p-holl** [comment]
Hi @Ashleyhoho, Since the smoke is passively advected, it does not actually afffect the dynamics. One way to count the smoke over time would be to perform the following steps at each time step

1. Sum the smoke in the bucket and increase the smoke counter.
2. Clear all smoke in the bucket by setting its density there to 0 (multiply by a bucket mask). This avoids counting the same smoke again in the future.

Cheers,
Philipp

**Comment by XiangZheng2002** [comment]
Thank you very much. I appreciate your explanation and understand the points you've made. Your guidance is invaluable to me! :)
